name: testing & quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    name: linting and tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry>=1.8.0,<2.0.0"

      - name: install project (incl. dev group)
        run: |
          poetry install --with dev

      - name: ruff lint
        run: poetry run ruff check alembic bionexus

      - name: ruff format check
        run: poetry run ruff format --check alembic bionexus
